// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://izniiomvacugbknrtyqu.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Iml6bmlpb212YWN1Z2JrbnJ0eXF1Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDg4MzAyNDMsImV4cCI6MjA2NDQwNjI0M30.OMz_UQuixXxPIJpb8BzCwXDXsM4qS7X__gNTGNM3Pds";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);